Declare variables required for report
Sometimes there are
```
Traceback (most recent call last):
  File "/usr/local/bin/depscan", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/depscan/cli.py", line 1118, in main
    vdr_file=vdr_file,
UnboundLocalError: local variable 'vdr_file' referenced before assignment
```
errors on depscan executions, thus declaring all variables used for the
reporting that are initialized only conditionally upfront.

Signed-off-by: Florian Heubeck <heubeck@mediamarktsaturn.com>