Fix undeclared vars for custom report creation.
Executing `depscan --report-template depscan.j2 --bom empty.json` with
`empty.json` being only `{}`, depscan fails with

```
Traceback (most recent call last):
  File "/home/heubeck/.local/bin/depscan", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/heubeck/.local/lib/python3.12/site-packages/depscan/cli.py", line 1041, in main                                                                                          pkg_vulnerabilities=pkg_vulnerabilities,
                        ^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'pkg_vulnerabilities' where it is not associated with a value
```

Added the with 5.1.6 newly introduced vars to the initialization similar
to the other variables provided to the jinja engine.

Signed-off-by: Florian Heubeck <heubeck@mediamarktsaturn.com>